name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: macOS-latest
    steps:
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@main

    - run: brew test-bot --only-cleanup-before

    - run: brew test-bot --only-tap-syntax

    - run: brew install bash fish

    - name: Validate shell syntax
      run: |
        set -xeuo pipefail

        bash -n handler.sh
        fish -n handler.fish
        zsh -n handler.sh

    - name: Run tests
      run: rake test
      env:
        HOMEBREW_COMMAND_NOT_FOUND_CI: 1
